// src/views/AdminDictionary.vue
<template>
  <div class="admin-dictionary">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>参数字典</span>
          <el-button type="primary" @click="dialogVisible = true">新增字典项</el-button>
        </div>
      </template>
      <el-alert
        title="维护项目类型、采购方式、资质类别、标段分类等系统选项，供业务表单统一引用。"
        type="info"
        show-icon
        :closable="false"
        style="margin-bottom: 20px"
      />
      <el-table :data="dicts" style="width: 100%" row-key="id" default-expand-all>
        <el-table-column prop="name" label="字典名称" min-width="200" />
        <el-table-column prop="code" label="字典编码" width="180" />
        <el-table-column prop="type" label="类型" width="120" />
        <el-table-column prop="status" label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="row.status === '启用' ? 'success' : 'info'">{{ row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="180">
          <template #default="{ row }">
            <el-button link type="primary" @click="edit(row)">编辑</el-button>
            <el-button link type="primary" @click="addChild(row)">新增子项</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="dialogVisible" title="新增字典项" width="600px">
      <el-form :model="form" label-width="100px">
        <el-form-item label="字典名称"><el-input v-model="form.name" /></el-form-item>
        <el-form-item label="字典编码"><el-input v-model="form.code" /></el-form-item>
        <el-form-item label="所属分类">
          <el-select v-model="form.parent" style="width: 100%">
            <el-option label="顶层分类" value="" />
            <el-option label="采购方式" value="purchase" />
            <el-option label="项目类型" value="project" />
            <el-option label="资质类别" value="qualification" />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="save">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'

const dicts = ref([
  {
    id: 1, name: '采购方式', code: 'purchase_mode', type: '分类', status: '启用',
    children: [
      { id: 11, name: '公开招标', code: 'open', type: '选项', status: '启用' },
      { id: 12, name: '邀请招标', code: 'invitation', type: '选项', status: '启用' },
      { id: 13, name: '公开询比价', code: 'inquiry', type: '选项', status: '启用' },
      { id: 14, name: '单一来源', code: 'single', type: '选项', status: '启用' },
    ]
  },
  {
    id: 2, name: '项目类型', code: 'project_type', type: '分类', status: '启用',
    children: [
      { id: 21, name: '工程', code: 'engineering', type: '选项', status: '启用' },
      { id: 22, name: '货物', code: 'goods', type: '选项', status: '启用' },
      { id: 23, name: '服务', code: 'service', type: '选项', status: '启用' },
    ]
  },
])

const dialogVisible = ref(false)
const form = reactive({ name: '', code: '', parent: '' })

const edit = (row) => alert(`编辑字典：${row.name}`)
const addChild = (row) => {
  form.parent = row.code
  dialogVisible.value = true
}
const save = () => {
  alert('字典项已保存')
  dialogVisible.value = false
}
</script>

<style scoped>
.admin-dictionary {
  max-width: 1100px;
  margin: 0 auto;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: bold;
}
</style>

// src/views/AdminDictionary.jsx
import { useState } from 'react'
import { Alert, Button, Card, Form, Input, Modal, Select, Table, Tag, message } from 'antd'

export default function AdminDictionary() {
  const [dicts] = useState([
    {
      id: 1, name: '采购方式', code: 'purchase_mode', type: '分类', status: '启用',
      children: [
        { id: 11, name: '公开招标', code: 'open', type: '选项', status: '启用' },
        { id: 12, name: '邀请招标', code: 'invitation', type: '选项', status: '启用' },
        { id: 13, name: '公开询比价', code: 'inquiry', type: '选项', status: '启用' },
        { id: 14, name: '单一来源', code: 'single', type: '选项', status: '启用' }
      ]
    },
    {
      id: 2, name: '项目类型', code: 'project_type', type: '分类', status: '启用',
      children: [
        { id: 21, name: '工程', code: 'engineering', type: '选项', status: '启用' },
        { id: 22, name: '货物', code: 'goods', type: '选项', status: '启用' },
        { id: 23, name: '服务', code: 'service', type: '选项', status: '启用' }
      ]
    }
  ])

  const [dialogVisible, setDialogVisible] = useState(false)
  const [form, setForm] = useState({ name: '', code: '', parent: '' })

  const updateField = (key, value) => {
    setForm((prev) => ({ ...prev, [key]: value }))
  }

  const edit = (row) => message.success(`编辑字典：${row.name}`)
  const addChild = (row) => {
    setForm((prev) => ({ ...prev, parent: row.code }))
    setDialogVisible(true)
  }
  const save = () => {
    message.success('字典项已保存')
    setDialogVisible(false)
  }

  const columns = [
    { title: '字典名称', dataIndex: 'name', minWidth: 200 },
    { title: '字典编码', dataIndex: 'code', width: 180 },
    { title: '类型', dataIndex: 'type', width: 120 },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      render: (status) => (
        <Tag color={status === '启用' ? 'success' : 'default'}>{status}</Tag>
      )
    },
    {
      title: '操作',
      width: 180,
      render: (_, row) => (
        <>
          <Button type="link" onClick={() => edit(row)}>编辑</Button>
          <Button type="link" onClick={() => addChild(row)}>新增子项</Button>
        </>
      )
    }
  ]

  return (
    <div className="admin-dictionary">
      <Card
        title={
          <div className="card-header">
            <span>参数字典</span>
            <Button type="primary" onClick={() => setDialogVisible(true)}>新增字典项</Button>
          </div>
        }
      >
        <Alert
          message="维护项目类型、采购方式、资质类别、标段分类等系统选项，供业务表单统一引用。"
          type="info"
          showIcon
          closable={false}
          style={{ marginBottom: 20 }}
        />
        <Table
          columns={columns}
          dataSource={dicts}
          rowKey="id"
          expandable={{ defaultExpandAllRows: true }}
          pagination={false}
          style={{ width: '100%' }}
        />
      </Card>

      <Modal
        title="新增字典项"
        open={dialogVisible}
        width={600}
        onCancel={() => setDialogVisible(false)}
        footer={[
          <Button key="cancel" onClick={() => setDialogVisible(false)}>取消</Button>,
          <Button key="save" type="primary" onClick={save}>保存</Button>
        ]}
      >
        <Form labelCol={{ flex: '0 0 100px' }} wrapperCol={{ flex: 'auto' }}>
          <Form.Item label="字典名称">
            <Input value={form.name} onChange={(e) => updateField('name', e.target.value)} />
          </Form.Item>
          <Form.Item label="字典编码">
            <Input value={form.code} onChange={(e) => updateField('code', e.target.value)} />
          </Form.Item>
          <Form.Item label="所属分类">
            <Select
              style={{ width: '100%' }}
              value={form.parent}
              onChange={(value) => updateField('parent', value)}
              options={[
                { label: '顶层分类', value: '' },
                { label: '采购方式', value: 'purchase' },
                { label: '项目类型', value: 'project' },
                { label: '资质类别', value: 'qualification' }
              ]}
            />
          </Form.Item>
        </Form>
      </Modal>

      <style>{`
        .admin-dictionary {
          max-width: 1100px;
          margin: 0 auto;
        }
        .admin-dictionary .card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-weight: bold;
          width: 100%;
        }
      `}</style>
    </div>
  )
}
