// src/views/AdminLogs.vue
<template>
  <div class="admin-logs">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>系统日志审计</span>
          <el-button type="primary" @click="exportLogs">导出日志</el-button>
        </div>
      </template>
      <el-alert
        title="记录系统操作、短信/邮件发送、关键业务操作日志，满足合规审计要求。"
        type="info"
        show-icon
        :closable="false"
        style="margin-bottom: 20px"
      />
      <el-row :gutter="20" style="margin-bottom: 20px">
        <el-col :span="6"><el-input v-model="search.operator" placeholder="操作人" clearable /></el-col>
        <el-col :span="6">
          <el-select v-model="search.type" placeholder="日志类型" clearable style="width: 100%">
            <el-option label="系统操作" value="system" />
            <el-option label="短信发送" value="sms" />
            <el-option label="邮件发送" value="email" />
            <el-option label="关键业务" value="business" />
          </el-select>
        </el-col>
        <el-col :span="6"><el-button type="primary" @click="load">查询</el-button></el-col>
      </el-row>
      <el-table :data="logs" style="width: 100%">
        <el-table-column prop="time" label="时间" width="180" />
        <el-table-column prop="type" label="类型" width="120" />
        <el-table-column prop="operator" label="操作人" width="150" />
        <el-table-column prop="action" label="操作内容" min-width="300" />
        <el-table-column prop="ip" label="IP" width="140" />
        <el-table-column prop="result" label="结果" width="100">
          <template #default="{ row }">
            <el-tag :type="row.result === '成功' ? 'success' : 'danger'">{{ row.result }}</el-tag>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'

const search = reactive({ operator: '', type: '' })
const logs = ref([
  { time: '2026-07-08 10:00:00', type: '系统操作', operator: 'admin', action: '登录系统', ip: '192.168.1.1', result: '成功' },
  { time: '2026-07-08 10:05:22', type: '关键业务', operator: '张三', action: '创建采购需求', ip: '192.168.1.10', result: '成功' },
  { time: '2026-07-08 10:30:11', type: '短信发送', operator: '系统', action: '向专家甲发送评标通知短信', ip: '-', result: '成功' },
  { time: '2026-07-08 11:00:45', type: '关键业务', operator: '李四', action: '发布招标公告', ip: '192.168.1.11', result: '成功' },
])

const load = () => alert('查询日志')
const exportLogs = () => alert('导出系统日志')
</script>

<style scoped>
.admin-logs {
  max-width: 1200px;
  margin: 0 auto;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: bold;
}
</style>

// src/views/AdminLogs.jsx
import { useState } from 'react'
import { Alert, Button, Card, Col, Input, Row, Select, Table, Tag, message } from 'antd'

export default function AdminLogs() {
  const [search, setSearch] = useState({ operator: '', type: undefined })
  const [logs] = useState([
    { time: '2026-07-08 10:00:00', type: '系统操作', operator: 'admin', action: '登录系统', ip: '192.168.1.1', result: '成功' },
    { time: '2026-07-08 10:05:22', type: '关键业务', operator: '张三', action: '创建采购需求', ip: '192.168.1.10', result: '成功' },
    { time: '2026-07-08 10:30:11', type: '短信发送', operator: '系统', action: '向专家甲发送评标通知短信', ip: '-', result: '成功' },
    { time: '2026-07-08 11:00:45', type: '关键业务', operator: '李四', action: '发布招标公告', ip: '192.168.1.11', result: '成功' }
  ])

  const load = () => message.success('查询日志')
  const exportLogs = () => message.success('导出系统日志')

  const columns = [
    { title: '时间', dataIndex: 'time', width: 180 },
    { title: '类型', dataIndex: 'type', width: 120 },
    { title: '操作人', dataIndex: 'operator', width: 150 },
    { title: '操作内容', dataIndex: 'action', minWidth: 300 },
    { title: 'IP', dataIndex: 'ip', width: 140 },
    {
      title: '结果',
      dataIndex: 'result',
      width: 100,
      render: (result) => (
        <Tag color={result === '成功' ? 'success' : 'error'}>{result}</Tag>
      )
    }
  ]

  return (
    <div className="admin-logs">
      <Card
        title={
          <div className="card-header">
            <span>系统日志审计</span>
            <Button type="primary" onClick={exportLogs}>导出日志</Button>
          </div>
        }
      >
        <Alert
          title="记录系统操作、短信/邮件发送、关键业务操作日志，满足合规审计要求。"
          type="info"
          showIcon
          closable={false}
          style={{ marginBottom: 20 }}
        />
        <Row gutter={20} style={{ marginBottom: 20 }}>
          <Col span={6}>
            <Input
              placeholder="操作人"
              allowClear
              value={search.operator}
              onChange={(e) => setSearch((prev) => ({ ...prev, operator: e.target.value }))}
            />
          </Col>
          <Col span={6}>
            <Select
              placeholder="日志类型"
              allowClear
              style={{ width: '100%' }}
              value={search.type}
              onChange={(value) => setSearch((prev) => ({ ...prev, type: value }))}
              options={[
                { label: '系统操作', value: 'system' },
                { label: '短信发送', value: 'sms' },
                { label: '邮件发送', value: 'email' },
                { label: '关键业务', value: 'business' }
              ]}
            />
          </Col>
          <Col span={6}>
            <Button type="primary" onClick={load}>查询</Button>
          </Col>
        </Row>
        <Table
          columns={columns}
          dataSource={logs}
          rowKey={(row) => `${row.time}-${row.operator}`}
          pagination={false}
          style={{ width: '100%' }}
        />
      </Card>

      <style>{`
        .admin-logs {
          max-width: 1200px;
          margin: 0 auto;
        }
        .admin-logs .card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-weight: bold;
          width: 100%;
        }
      `}</style>
    </div>
  )
}
