// src/views/BidderInvoices.vue
<template>
  <div class="bidder-invoices">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>发票申请</span>
          <el-button type="primary" @click="dialogVisible = true">申请发票</el-button>
        </div>
      </template>
      <el-alert
        title="仅对已缴纳且审核通过的费用申请发票，开票后可在列表下载电子发票。"
        type="info"
        show-icon
        :closable="false"
        style="margin-bottom: 20px"
      />
      <el-table :data="invoices" style="width: 100%">
        <el-table-column prop="project" label="关联项目" min-width="260" />
        <el-table-column prop="feeType" label="费用类型" width="140" />
        <el-table-column prop="amount" label="开票金额" width="120" />
        <el-table-column prop="type" label="发票类型" width="120" />
        <el-table-column prop="status" label="状态" width="120">
          <template #default="{ row }">
            <el-tag :type="statusType(row.status)">{{ row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="120">
          <template #default="{ row }">
            <el-button v-if="row.status === '已开票'" link type="primary" @click="download(row)">下载</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="dialogVisible" title="申请发票" width="600px">
      <el-form :model="form" label-width="100px">
        <el-form-item label="关联费用">
          <el-select v-model="form.feeId" placeholder="请选择已缴纳费用" style="width: 100%">
            <el-option label="XX市轨道交通设备采购项目-招标文件费 500元" value="1" />
          </el-select>
        </el-form-item>
        <el-form-item label="发票类型">
          <el-radio-group v-model="form.type">
            <el-radio label="增值税普通发票">增值税普通发票</el-radio>
            <el-radio label="增值税专用发票">增值税专用发票</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="开票抬头">
          <el-input v-model="form.title" placeholder="请输入发票抬头" />
        </el-form-item>
        <el-form-item label="纳税人识别号">
          <el-input v-model="form.taxNo" placeholder="请输入税号" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submit">提交申请</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'

const dialogVisible = ref(false)
const invoices = ref([
  { project: 'XX市轨道交通设备采购项目', feeType: '招标文件费', amount: 500, type: '增值税普通发票', status: '已开票' },
  { project: '办公桌椅采购项目', feeType: '招标文件费', amount: 300, type: '增值税普通发票', status: '审核中' },
])

const form = reactive({
  feeId: '',
  type: '增值税普通发票',
  title: '',
  taxNo: ''
})

const statusType = (s) => {
  const map = { '审核中': 'warning', '已开票': 'success', '已驳回': 'danger' }
  return map[s] || ''
}

const download = (row) => {
  alert(`下载电子发票：${row.project}`)
}

const submit = () => {
  alert('发票申请已提交')
  dialogVisible.value = false
}
</script>

<style scoped>
.bidder-invoices {
  max-width: 1100px;
  margin: 0 auto;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: bold;
}
</style>

// src/views/BidderInvoices.jsx
import { useState } from 'react'
import { Alert, Button, Card, Form, Input, Modal, Radio, Select, Table, Tag, message } from 'antd'

export default function BidderInvoices() {
  const [dialogVisible, setDialogVisible] = useState(false)

  const [invoices] = useState([
    { project: 'XX市轨道交通设备采购项目', feeType: '招标文件费', amount: 500, type: '增值税普通发票', status: '已开票' },
    { project: '办公桌椅采购项目', feeType: '招标文件费', amount: 300, type: '增值税普通发票', status: '审核中' }
  ])

  const [form, setForm] = useState({
    feeId: '',
    type: '增值税普通发票',
    title: '',
    taxNo: ''
  })

  const updateField = (key, value) => {
    setForm((prev) => ({ ...prev, [key]: value }))
  }

  const statusColor = (s) => {
    const map = { 审核中: 'warning', 已开票: 'success', 已驳回: 'error' }
    return map[s] || 'default'
  }

  const download = (row) => {
    message.success(`下载电子发票：${row.project}`)
  }

  const submit = () => {
    message.success('发票申请已提交')
    setDialogVisible(false)
  }

  const columns = [
    { title: '关联项目', dataIndex: 'project', key: 'project', minWidth: 260 },
    { title: '费用类型', dataIndex: 'feeType', key: 'feeType', width: 140 },
    { title: '开票金额', dataIndex: 'amount', key: 'amount', width: 120 },
    { title: '发票类型', dataIndex: 'type', key: 'type', width: 120 },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 120,
      render: (status) => <Tag color={statusColor(status)}>{status}</Tag>
    },
    {
      title: '操作',
      key: 'action',
      width: 120,
      render: (_, row) =>
        row.status === '已开票' && (
          <Button type="link" onClick={() => download(row)}>下载</Button>
        )
    }
  ]

  return (
    <div className="bidder-invoices">
      <Card
        title={
          <div className="card-header">
            <span>发票申请</span>
            <Button type="primary" onClick={() => setDialogVisible(true)}>申请发票</Button>
          </div>
        }
      >
        <Alert
          message="仅对已缴纳且审核通过的费用申请发票，开票后可在列表下载电子发票。"
          type="info"
          showIcon
          closable={false}
          style={{ marginBottom: 20 }}
        />
        <Table
          columns={columns}
          dataSource={invoices}
          rowKey="project"
          pagination={false}
          style={{ width: '100%' }}
        />
      </Card>

      <Modal
        title="申请发票"
        open={dialogVisible}
        width={600}
        onCancel={() => setDialogVisible(false)}
        footer={[
          <Button key="cancel" onClick={() => setDialogVisible(false)}>取消</Button>,
          <Button key="submit" type="primary" onClick={submit}>提交申请</Button>
        ]}
      >
        <Form labelCol={{ flex: '0 0 100px' }} wrapperCol={{ flex: 'auto' }}>
          <Form.Item label="关联费用">
            <Select
              value={form.feeId || undefined}
              onChange={(value) => updateField('feeId', value)}
              placeholder="请选择已缴纳费用"
              style={{ width: '100%' }}
              options={[{ label: 'XX市轨道交通设备采购项目-招标文件费 500元', value: '1' }]}
            />
          </Form.Item>
          <Form.Item label="发票类型">
            <Radio.Group
              value={form.type}
              onChange={(e) => updateField('type', e.target.value)}
            >
              <Radio value="增值税普通发票">增值税普通发票</Radio>
              <Radio value="增值税专用发票">增值税专用发票</Radio>
            </Radio.Group>
          </Form.Item>
          <Form.Item label="开票抬头">
            <Input
              value={form.title}
              onChange={(e) => updateField('title', e.target.value)}
              placeholder="请输入发票抬头"
            />
          </Form.Item>
          <Form.Item label="纳税人识别号">
            <Input
              value={form.taxNo}
              onChange={(e) => updateField('taxNo', e.target.value)}
              placeholder="请输入税号"
            />
          </Form.Item>
        </Form>
      </Modal>

      <style>{`
        .bidder-invoices {
          max-width: 1100px;
          margin: 0 auto;
        }
        .bidder-invoices .card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-weight: bold;
        }
      `}</style>
    </div>
  )
}
