// src/views/BidRegister.vue
<template>
  <div class="bid-register">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>项目报名</span>
          <el-tag type="primary">项目：XX市轨道交通设备采购项目</el-tag>
        </div>
      </template>

      <el-steps :active="0" finish-status="success" simple style="margin-bottom: 20px">
        <el-step title="提交报名" />
        <el-step title="资质审核" />
        <el-step title="报名成功" />
      </el-steps>

      <el-alert
        title="请确认贵司符合招标公告中的资格要求，提交后将进入招标方审核。"
        type="info"
        show-icon
        :closable="false"
        style="margin-bottom: 20px"
      />

      <el-form
        ref="formRef"
        :model="form"
        :rules="rules"
        label-width="140px"
        class="register-form"
      >
        <el-form-item label="报名标段" prop="packages">
          <el-checkbox-group v-model="form.packages">
            <el-checkbox label="B1">第一标段：主设备</el-checkbox>
            <el-checkbox label="B2">第二标段：辅材</el-checkbox>
          </el-checkbox-group>
        </el-form-item>
        <el-form-item label="联系人" prop="contact">
          <el-input v-model="form.contact" placeholder="请输入联系人姓名" />
        </el-form-item>
        <el-form-item label="联系电话" prop="phone">
          <el-input v-model="form.phone" placeholder="请输入联系电话" />
        </el-form-item>
        <el-form-item label="电子邮箱" prop="email">
          <el-input v-model="form.email" placeholder="请输入电子邮箱" />
        </el-form-item>
        <el-form-item label="资质文件" prop="files">
          <el-upload
            ref="uploadRef"
            action="#"
            :auto-upload="false"
            :file-list="fileList"
            multiple
            drag
            style="width: 100%"
            @change="handleFileChange"
          >
            <el-icon :size="40"><Upload /></el-icon>
            <div class="el-upload__text">拖拽文件到此处或 <em>点击上传</em></div>
          </el-upload>
        </el-form-item>
        <el-form-item label="备注说明">
          <el-input v-model="form.remark" type="textarea" :rows="3" placeholder="其他需要说明的内容" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submit">提交报名</el-button>
          <el-button @click="$router.push('/admin/bidder-projects')">返回项目中心</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { Upload } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'

const router = useRouter()
const formRef = ref(null)
const uploadRef = ref(null)
const fileList = ref([])

const validatePhone = (rule, value, callback) => {
  if (!value) {
    callback(new Error('请输入联系电话'))
    return
  }
  const phoneReg = /^1[3-9]\d{9}$/
  const telReg = /^0\d{2,3}-?\d{7,8}$/
  if (!phoneReg.test(value) && !telReg.test(value)) {
    callback(new Error('请输入有效的手机号或座机号'))
  } else {
    callback()
  }
}

const validateEmail = (rule, value, callback) => {
  if (!value) {
    callback(new Error('请输入电子邮箱'))
    return
  }
  const emailReg = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!emailReg.test(value)) {
    callback(new Error('请输入有效的电子邮箱'))
  } else {
    callback()
  }
}

const rules = {
  packages: [{ required: true, message: '请至少选择一个标段', trigger: 'change', type: 'array' }],
  contact: [{ required: true, message: '请输入联系人姓名', trigger: 'blur' }],
  phone: [{ required: true, validator: validatePhone, trigger: 'blur' }],
  email: [{ required: true, validator: validateEmail, trigger: 'blur' }],
  files: [{ required: true, message: '请上传资质文件', trigger: 'change' }]
}

const form = reactive({
  packages: ['B1'],
  contact: '',
  phone: '',
  email: '',
  remark: ''
})

const handleFileChange = () => {
  form.files = fileList.value.length > 0 ? fileList.value : null
}

const submit = async () => {
  const valid = await formRef.value.validate().catch(() => false)
  if (!valid) return
  if (fileList.value.length === 0) {
    ElMessage.warning('请上传资质文件')
    return
  }
  ElMessage.success('报名申请已提交，状态：待审核')
  router.push('/admin/bidder-projects')
}
</script>

<style scoped>
.bid-register {
  max-width: 900px;
  margin: 0 auto;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: bold;
}

.register-form {
  margin-top: 10px;
}
</style>

// src/views/BidRegister.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Alert, Button, Card, Checkbox, Form, Input, Steps, Tag, Upload, message } from 'antd'
import { UploadOutlined } from '@ant-design/icons'

export default function BidRegister() {
  const navigate = useNavigate()
  const [form] = Form.useForm()
  const [fileList, setFileList] = useState([])

  const validatePhone = (_, value) => {
    if (!value) {
      return Promise.reject(new Error('请输入联系电话'))
    }
    const phoneReg = /^1[3-9]\d{9}$/
    const telReg = /^0\d{2,3}-?\d{7,8}$/
    if (!phoneReg.test(value) && !telReg.test(value)) {
      return Promise.reject(new Error('请输入有效的手机号或座机号'))
    }
    return Promise.resolve()
  }

  const validateEmail = (_, value) => {
    if (!value) {
      return Promise.reject(new Error('请输入电子邮箱'))
    }
    const emailReg = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailReg.test(value)) {
      return Promise.reject(new Error('请输入有效的电子邮箱'))
    }
    return Promise.resolve()
  }

  const rules = {
    packages: [{ required: true, type: 'array', message: '请至少选择一个标段' }],
    contact: [{ required: true, message: '请输入联系人姓名' }],
    phone: [{ required: true, validator: validatePhone }],
    email: [{ required: true, validator: validateEmail }]
  }

  const submit = async () => {
    const values = await form.validateFields().catch(() => null)
    if (!values) return
    if (fileList.length === 0) {
      message.warning('请上传资质文件')
      return
    }
    message.success('报名申请已提交，状态：待审核')
    navigate('/admin/bidder-projects')
  }

  return (
    <div className="bid-register">
      <Card
        title={
          <div className="card-header">
            <span>项目报名</span>
            <Tag color="blue">项目：XX市轨道交通设备采购项目</Tag>
          </div>
        }
      >
        <Steps
          size="small"
          current={0}
          style={{ marginBottom: 20 }}
          items={['提交报名', '资质审核', '报名成功'].map((title) => ({ title }))}
        />

        <Alert
          message="请确认贵司符合招标公告中的资格要求，提交后将进入招标方审核。"
          type="info"
          showIcon
          closable={false}
          style={{ marginBottom: 20 }}
        />

        <Form
          form={form}
          initialValues={{ packages: ['B1'] }}
          labelCol={{ flex: '0 0 140px' }}
          wrapperCol={{ flex: 'auto' }}
          className="register-form"
        >
          <Form.Item label="报名标段" name="packages" rules={rules.packages}>
            <Checkbox.Group>
              <Checkbox value="B1">第一标段：主设备</Checkbox>
              <Checkbox value="B2">第二标段：辅材</Checkbox>
            </Checkbox.Group>
          </Form.Item>
          <Form.Item label="联系人" name="contact" rules={rules.contact}>
            <Input placeholder="请输入联系人姓名" />
          </Form.Item>
          <Form.Item label="联系电话" name="phone" rules={rules.phone}>
            <Input placeholder="请输入联系电话" />
          </Form.Item>
          <Form.Item label="电子邮箱" name="email" rules={rules.email}>
            <Input placeholder="请输入电子邮箱" />
          </Form.Item>
          <Form.Item label="资质文件" required>
            <Upload.Dragger
              fileList={fileList}
              onChange={({ fileList: next }) => setFileList(next)}
              beforeUpload={() => false}
              multiple
            >
              <p className="ant-upload-drag-icon">
                <UploadOutlined style={{ fontSize: 40 }} />
              </p>
              <p className="ant-upload-text">拖拽文件到此处或 <em>点击上传</em></p>
            </Upload.Dragger>
          </Form.Item>
          <Form.Item label="备注说明" name="remark">
            <Input.TextArea rows={3} placeholder="其他需要说明的内容" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" onClick={submit}>提交报名</Button>
            <Button style={{ marginLeft: 8 }} onClick={() => navigate('/admin/bidder-projects')}>
              返回项目中心
            </Button>
          </Form.Item>
        </Form>
      </Card>

      <style>{`
        .bid-register {
          max-width: 900px;
          margin: 0 auto;
        }
        .bid-register .card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-weight: bold;
        }
        .bid-register .register-form {
          margin-top: 10px;
        }
      `}</style>
    </div>
  )
}
