// src/views/Register.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Button,
  Tabs,
  Form,
  Input,
  Upload,
  Checkbox,
  message
} from 'antd'
import { UploadOutlined } from '@ant-design/icons'

export default function Register() {
  const navigate = useNavigate()
  const [form] = Form.useForm()
  const [role, setRole] = useState('tenderee')
  const [fileList, setFileList] = useState([])

  const submit = () => {
    form.validateFields().then(() => {
      message.success('注册信息已提交，等待平台审核')
      navigate('/login')
    })
  }

  const uploadProps = {
    fileList,
    onChange: ({ fileList: newFileList }) => setFileList(newFileList),
    beforeUpload: () => false,
    multiple: true
  }

  const renderCommonFields = () => (
    <>
      <Form.Item
        label="手机号"
        name="phone"
        rules={[{ required: true, message: '请输入手机号' }]}
      >
        <Input placeholder="请输入手机号" />
      </Form.Item>
      <Form.Item
        label="登录密码"
        name="password"
        rules={[{ required: true, message: '请设置登录密码' }]}
      >
        <Input.Password placeholder="请设置登录密码" />
      </Form.Item>
    </>
  )

  const agreementRule = {
    validator: (_, value) =>
      value ? Promise.resolve() : Promise.reject(new Error('请阅读并同意用户协议'))
  }

  const renderOrgForm = (isTenderee) => (
    <Form form={form} layout="vertical">
      <Form.Item
        label={isTenderee ? '单位名称' : '企业名称'}
        name="companyName"
        rules={[{ required: true, message: isTenderee ? '请输入单位全称' : '请输入企业全称' }]}
      >
        <Input placeholder={isTenderee ? '请输入单位全称' : '请输入企业全称'} />
      </Form.Item>
      <Form.Item
        label="统一社会信用代码"
        name="creditCode"
        rules={[{ required: true, message: '请输入统一社会信用代码' }]}
      >
        <Input placeholder="请输入统一社会信用代码" />
      </Form.Item>
      <Form.Item
        label="联系人"
        name="contactName"
        rules={[{ required: true, message: '请输入联系人姓名' }]}
      >
        <Input placeholder="请输入联系人姓名" />
      </Form.Item>
      {renderCommonFields()}
      <Form.Item label="资质附件">
        <Upload {...uploadProps}>
          <Button icon={<UploadOutlined />}>上传营业执照等资质</Button>
        </Upload>
      </Form.Item>
      <Form.Item
        name="agreed"
        valuePropName="checked"
        rules={[agreementRule]}
      >
        <Checkbox>我已阅读并同意《平台用户协议》</Checkbox>
      </Form.Item>
    </Form>
  )

  const expertForm = (
    <Form form={form} layout="vertical">
      <Form.Item
        label="姓名"
        name="contactName"
        rules={[{ required: true, message: '请输入姓名' }]}
      >
        <Input placeholder="请输入姓名" />
      </Form.Item>
      <Form.Item
        label="身份证号"
        name="idCard"
        rules={[{ required: true, message: '请输入身份证号' }]}
      >
        <Input placeholder="请输入身份证号" />
      </Form.Item>
      <Form.Item
        label="专业领域"
        name="expertField"
        rules={[{ required: true, message: '请输入专业领域' }]}
      >
        <Input placeholder="例如：电子信息、机械设备" />
      </Form.Item>
      {renderCommonFields()}
      <Form.Item label="资质附件">
        <Upload {...uploadProps}>
          <Button icon={<UploadOutlined />}>上传职称证书等</Button>
        </Upload>
      </Form.Item>
    </Form>
  )

  const tabItems = [
    { key: 'tenderee', label: '招标人注册', children: renderOrgForm(true) },
    { key: 'bidder', label: '供应商注册', children: renderOrgForm(false) },
    { key: 'expert', label: '专家注册', children: expertForm }
  ]

  return (
    <div className="register-page">
      <div className="register-container">
        <h2>平台注册</h2>
        <Tabs activeKey={role} onChange={setRole} type="card" items={tabItems} />
        <div className="actions">
          <Button type="primary" size="large" style={{ width: '100%' }} onClick={submit}>提交注册</Button>
          <div className="login-link">
            已有账号？<Button type="link" onClick={() => navigate('/login')}>立即登录</Button>
          </div>
        </div>
      </div>

      <style>{`
        .register-page {
          min-height: 100vh;
          background: linear-gradient(135deg, #001529 0%, #003366 100%);
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 40px 20px;
        }
        .register-container {
          width: 520px;
          background: #fff;
          border-radius: 8px;
          padding: 32px;
          box-shadow: 0 10px 40px rgba(0,0,0,0.3);
        }
        .register-container h2 {
          text-align: center;
          margin-bottom: 24px;
          color: #001529;
        }
        .actions {
          margin-top: 24px;
        }
        .login-link {
          margin-top: 16px;
          text-align: center;
          color: #666;
        }
      `}</style>
    </div>
  )
}

// src/views/Register.vue
<template>
  <div class="register-page">
    <div class="register-container">
      <h2>平台注册</h2>
      <el-tabs v-model="form.role" type="border-card">
        <el-tab-pane label="供应商注册" name="bidder">
          <el-form :model="form" label-position="top">
            <el-form-item label="企业名称" required>
              <el-input v-model="form.companyName" placeholder="请输入企业全称" />
            </el-form-item>
            <el-form-item label="统一社会信用代码" required>
              <el-input v-model="form.creditCode" placeholder="请输入统一社会信用代码" />
            </el-form-item>
            <el-form-item label="联系人" required>
              <el-input v-model="form.contactName" placeholder="请输入联系人姓名" />
            </el-form-item>
            <el-form-item label="手机号" required>
              <el-input v-model="form.phone" placeholder="请输入手机号" />
            </el-form-item>
            <el-form-item label="登录密码" required>
              <el-input v-model="form.password" type="password" placeholder="请设置登录密码" />
            </el-form-item>
            <el-form-item label="资质附件">
              <el-upload action="#" :auto-upload="false" :file-list="fileList" multiple>
                <el-button type="primary">上传营业执照等资质</el-button>
              </el-upload>
            </el-form-item>
            <el-form-item>
              <el-checkbox v-model="form.agreed">我已阅读并同意《平台用户协议》</el-checkbox>
            </el-form-item>
          </el-form>
        </el-tab-pane>
        <el-tab-pane label="专家注册" name="expert">
          <el-form :model="form" label-position="top">
            <el-form-item label="姓名" required>
              <el-input v-model="form.contactName" placeholder="请输入姓名" />
            </el-form-item>
            <el-form-item label="身份证号" required>
              <el-input v-model="form.idCard" placeholder="请输入身份证号" />
            </el-form-item>
            <el-form-item label="专业领域" required>
              <el-input v-model="form.expertField" placeholder="例如：电子信息、机械设备" />
            </el-form-item>
            <el-form-item label="手机号" required>
              <el-input v-model="form.phone" placeholder="请输入手机号" />
            </el-form-item>
            <el-form-item label="登录密码" required>
              <el-input v-model="form.password" type="password" placeholder="请设置登录密码" />
            </el-form-item>
            <el-form-item label="资质附件">
              <el-upload action="#" :auto-upload="false" :file-list="fileList" multiple>
                <el-button type="primary">上传职称证书等</el-button>
              </el-upload>
            </el-form-item>
          </el-form>
        </el-tab-pane>
      </el-tabs>
      <div class="actions">
        <el-button type="primary" size="large" style="width: 100%" @click="submit">提交注册</el-button>
        <div class="login-link">
          已有账号？<el-link type="primary" @click="$router.push('/login')">立即登录</el-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()

const form = reactive({
  role: 'bidder',
  companyName: '',
  creditCode: '',
  contactName: '',
  phone: '',
  password: '',
  idCard: '',
  expertField: '',
  agreed: false
})

const fileList = ref([])

const submit = () => {
  alert('注册信息已提交，等待平台审核')
  router.push('/login')
}
</script>

<style scoped>
.register-page {
  min-height: 100vh;
  background: linear-gradient(135deg, #001529 0%, #003366 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px 20px;
}

.register-container {
  width: 520px;
  background: #fff;
  border-radius: 8px;
  padding: 32px;
  box-shadow: 0 10px 40px rgba(0,0,0,0.3);
}

.register-container h2 {
  text-align: center;
  margin-bottom: 24px;
  color: #001529;
}

.actions {
  margin-top: 24px;
}

.login-link {
  margin-top: 16px;
  text-align: center;
  color: #666;
}
</style>
