// src/components/EmptyState.vue
<template>
  <div class="empty-state">
    <el-empty :description="description">
      <template #image>
        <el-icon :size="64" :color="iconColor">
          <component :is="icon" />
        </el-icon>
      </template>
      <template v-if="$slots.default">
        <slot />
      </template>
      <template v-else-if="actionText">
        <el-button :type="actionType" @click="$emit('action')">{{ actionText }}</el-button>
      </template>
    </el-empty>
  </div>
</template>

<script setup>
import { computed } from 'vue'

defineProps({
  description: { type: String, default: '暂无数据' },
  icon: { type: String, default: 'Document' },
  iconColor: { type: String, default: '#C0C4CC' },
  actionText: { type: String, default: '' },
  actionType: { type: String, default: 'primary' }
})

defineEmits(['action'])
</script>

<style scoped>
.empty-state {
  padding: 40px 0;
}
</style>

// src/components/EmptyState.jsx
import { Empty, Button } from 'antd'
import {
  FileTextOutlined,
  FolderOpenOutlined,
  InboxOutlined
} from '@ant-design/icons'

const ICON_MAP = {
  Document: FileTextOutlined,
  Folder: FolderOpenOutlined,
  Box: InboxOutlined
}

export default function EmptyState({
  description = '暂无数据',
  icon = 'Document',
  iconColor = '#C0C4CC',
  actionText = '',
  actionType = 'primary',
  children,
  onAction
}) {
  const IconComponent = ICON_MAP[icon] || FileTextOutlined

  const extra = children || (actionText ? (
    <Button type={actionType} onClick={onAction}>
      {actionText}
    </Button>
  ) : null)

  return (
    <div className="empty-state" style={{ padding: '40px 0' }}>
      <Empty
        description={description}
        image={<IconComponent style={{ fontSize: 64, color: iconColor }} />}
      >
        {extra}
      </Empty>
    </div>
  )
}
