// src/components/Forbidden.jsx
import { Result, Button } from 'antd'
import { useNavigate } from 'react-router-dom'
import { useRole } from '../hooks/useRole.js'

const HOME_MAP = {
  tenderee: '/admin/dashboard',
  agent: '/admin/dashboard',
  bidder: '/admin/dashboard',
  expert: '/admin/dashboard',
  supervisor: '/admin/supervisor-hall',
  admin: '/admin/admin-dashboard'
}

export default function Forbidden() {
  const navigate = useNavigate()
  const { role, roleName } = useRole()

  const subtitle = `当前身份：${roleName}，您没有权限查看该页面。`

  function goHome() {
    navigate(HOME_MAP[role] || '/admin/dashboard')
  }

  return (
    <div className="forbidden-page" style={{
      minHeight: '60vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center'
    }}>
      <Result
        status="403"
        title="无权限访问"
        subTitle={subtitle}
        extra={
          <Button type="primary" onClick={goHome}>
            返回我的工作台
          </Button>
        }
      />
    </div>
  )
}

// src/components/Forbidden.vue
<template>
  <div class="forbidden-page">
    <el-result icon="warning" title="无权限访问" :sub-title="subtitle">
      <template #extra>
        <el-button type="primary" @click="goHome">返回我的工作台</el-button>
      </template>
    </el-result>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useRole } from '../composables/useRole.js'

const router = useRouter()
const { roleName } = useRole()

const subtitle = computed(() => `当前身份：${roleName.value}，您没有权限查看该页面。`)

function goHome() {
  const map = {
    tenderee: '/admin/dashboard',
    agent: '/admin/dashboard',
    bidder: '/admin/dashboard',
    expert: '/admin/dashboard',
    supervisor: '/admin/supervisor-hall',
    admin: '/admin/admin-dashboard'
  }
  const { role } = useRole()
  router.push(map[role.value] || '/admin/dashboard')
}
</script>

<style scoped>
.forbidden-page {
  min-height: 60vh;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>
